# Generated by Django 5.0.7 on 2024-09-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_medicalrecord_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_hash', models.CharField(editable=False, max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
